### ISSUE TITLE
Link Postgres to Rails container in dev/test

### ISSUE THREAD

**Issue by mdarby** [getcarina/carina-oauth#29]

**Comment by carolynvs** [comment]
Right now the way I am running dev/test is that the rails app is connecting using the published postgres port. That way I can still connect using a postgres client to see the data.

What's the upside to using a link?

**Comment by mdarby** [comment]
If I don't link the pg container I get the "could not connect to 'postgres' host" error from ActiveRecord...

**Comment by mdarby** [comment]
Do you have PG running locally (outside of Docker)?

**Comment by carolynvs** [comment]
Postgres is running in a container along side the rails-1 container. In **postgresql.sh**, I am publishing the postgres port publicly so that I can connect to it from the rails container and from my own machine.

```
docker run \
    -d -p 5432:5432 \
    --name postgres \
......
```

Then in my vars file I have this:

export POSTGRES_HOST=104.130.134.163

where the ip address is the result of me running `docker-machine env carina-oauth`.

**Comment by mdarby** [comment]
I'll roll with that method :)
